### ISSUE TITLE
-p, --pass do not work with or without password present

### ISSUE THREAD

**Issue by blackbird1999** [stefanberger/ima-evm-utils#2]
-p
--pass 
-p password
--pass password
all fail.

**Comment by blackbird1999** [comment]
Ah, no space is allowed between -p and password. So -ppassword works. I'm not sure what's up with -p and --pass without a password.  In the end, the help output is simply incorrect.

**Comment by stefanberger** [comment]
Sorry, this is not the upstream repository. You have to report your findings either to https://github.com/mimizohar/ima-evm-utils or to the linux integrity mailing list.
